### ISSUE TITLE
Egy nagy ZIP az osszes szukseges kiegeszitovel

### ISSUE THREAD

**Issue by stooone** [nhadrian/X-plane_HungaryVFR#1]
Jolenne egy nagy ZIP amiben a sceneryhez kello (es remelhetoleg legfrisebb verzioju) osszes szukseges kiegeszito benne lenne.

**Comment by nhadrian** [comment]
Szia. Sajnos ez nem kivitelezhető jelenleg, egyrészt a library-kat övező szerzői jogok miatt, másrészt több száz mega - ha nem gigabájt lenne a mérete. Egyenlőre marad a Readme-kben való hivatkozás.

**Comment by stooone** [comment]
A méret még nem is lenne gond, de a szerzői jogok... Jogos.
