### ISSUE TITLE
Error with scenery file "atc.dat" (ATC_parser.cpp:1063.)

### ISSUE THREAD

**Issue by stooone** [nhadrian/X-plane_HungaryVFR#2]
0:00:34.301 E/SYS: +-------------------------------------------------------------------------------
0:00:34.301 E/SYS: | There was a problem loading the scenery package:
0:00:34.301 E/SYS: | Custom Scenery/HungaryVFR-Scenery-Budapest/
0:00:34.301 E/SYS: | The scenery may not look correct.
0:00:34.301 E/SYS: | Please see the Log.txt file for detailed error information.
0:00:34.301 E/SYS: | (ATC_parser.cpp:923)
0:00:34.301 E/SYS: +-------------------------------------------------------------------------------
0:00:34.301 E/SCN: Custom Scenery/HungaryVFR-Scenery-Budapest/Earth nav data/atc.dat:
0:00:34.301 E/SCN: Invalid ICAO code found!
0:00:34.301 E/SCN: ***Error with scenery file "atc.dat" (ATC_parser.cpp:1063.)***
0:00:34.301 E/SCN: Found fatal error!

commit 53cc6e2a9212d80b80f1d930e5c57450ae179742 (HEAD -> HungaryVFR-Release, origin/HungaryVFR-Release)

**Comment by nhadrian** [comment]
@darealgege Rá tudsz erre nézni?

**Comment by stooone** [comment]
Sikerult megoldanom a problemat. Miutan a HungaryVFR-Scenery-Budapest branch-on nem letezik az a file feltelteleztem, hogy esetleg veletlenul kerult bele a HungaryVFR-Release-be, miutan kitoroltem hiba nelkul elindult a sim.

Nem vagyok otthon a scenery keszitesben, igy gozom sincs, hogy ez igy most jo-e vagy sem, de legalabb mukodik!:)
